### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by harrisosserman** [harrisosserman/word2vec#3]
- [x] Speed up each iteration (currently takes too long)
- [x] Run the code on a server
- [x] Remove words from corpus that happen less than 5 times 
- [x] Find 10 words most similar to "hello"

**Comment by harrisosserman** [comment]
To install node on ec2 server: http://stackoverflow.com/questions/27350634/how-to-yum-install-node-js-on-amazon-linux

**Comment by harrisosserman** [comment]
To install git: `sudo yum install git-all`

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
